config/routes.rb
Rails.application.routes.draw do
  get "up" => "rails/health#show", as: :rails_health_check
  root 'pages#home'
  get  'about', to:'pages#about'
  resources :articles
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  validates :title , presence: true, length: {minimum: 6 , maximum: 100}
  validates :description, presence: true, length: {minimum: 10 , maximum: 300}
end

app/models/user.rb
class User < ApplicationRecord
  before_save {self.email = email.downcase}
  has_many :articles
  has_secure_password
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :username, presence: true, uniqueness: { case_sensitive: false }, 
                       length: { minimum: 3, maximum: 25 }

  validates :email, presence: true, uniqueness: { case_sensitive: false }, 
                    length: { maximum: 105 }, 
                    format: { with: VALID_EMAIL_REGEX }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def show
    @article = Article.find(params[:id])
  end
  def index
    @articles = Article.all
  end
  def new
    @article = Article.new
  end
  def edit
    @article = Article.find(params[:id])
  end
  def create
    @article = Article.new(params.require(:article).permit(:title, :description))
    @article.user = User.first
    if @article.save
      flash[:notice] ="Article created successfully"
      redirect_to @article
    else
      puts @article.errors.full_messages
      render :new
    end
  end
  def update
    @article = Article.find(params[:id])
    if @article.update(params.require(:article).permit(:title, :description))
      flash[:notice] = "Article updated successfully"
      redirect_to @article
    else
      render :edit
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    flash[:notice] = "Article deleted successfully"
    redirect_to articles_path
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/views/articles/edit.html.erb
<h1>Edit article</h1>

<% if @article.errors.any? %>
  <h2 style="color:red">Please Take Care of these Errors</h2>
  <ul style="color:red">
    <% @article.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>


<%= form_with(model: @article, local: true, data: { turbo: false }) do |f| %>

<p>
    <%= f.label :title%> <br>
    <%= f.text_field :title%>
</p>
<p>
    <%= f.label :description%> <br>
    <%= f.text_area :description%>
</p>
<p>
  <%= f.submit%>  
</p>
<%end%>

<%= link_to 'Cancel and Return to  Articles listing', articles_path, data: { confirm: 'Are you sure?' } %>

app/views/articles/index.html.erb
<h1>All Articles</h1>
<table>
    <thead>
        <tr>
            <th>Title</th>
            <th>Description</th>
            <th>Actions</th>
            <th>User</th>
        </tr>
    </thead>
    <tbody>
        <% @articles.each do |article|%>
        <tr>
            <td><%= article.title%></td>
            <td><%= article.description%></td>
           <td><%= link_to 'Delete', article_path(article), data: { turbo_method: :delete, confirm: 'Are you sure?' } %>
          <%= link_to 'Show', article_path(article), data: { turbo_method: :get, confirm: 'Are you sure?' } %>
         <%= link_to 'Update', edit_article_path(article) %></td>
           <td><%= article.user.username %></td>
        </tr>
        <%end%>

          <td><button><%= link_to 'Add Article', new_article_path %></td>
    </tbody>
</table>

app/views/articles/new.html.erb
<h1>Create a new article</h1>

<% if @article.errors.any? %>
  <h2 style="color:red">Please Take Care of these Errors</h2>
  <ul>
    <% @article.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>


<%= form_with model: @article, url: articles_path, local: true, data: { turbo: false } do |f| %>
<p>
    <%= f.label :title%> <br>
    <%= f.text_field :title%>
</p>
<p>
    <%= f.label :description%> <br>
    <%= f.text_area :description%>
</p>
<p>
  <%= f.submit%>  
</p>
<%end%>

<%= link_to 'Return to Articles listing', articles_path, data: { confirm: 'Are you sure?' } %>

app/views/articles/show.html.erb
<h1>Showing Articles Details</h1>
<p><strong>By:</strong><%= @article.user.username %></p>
<p><strong>Title:</strong><%= @article.title%></p>
<p><strong>Description:</strong><%= @article.description%></p>
<%= link_to 'Delete', article_path(@article), data: { turbo_method: :delete, confirm: 'Are you sure?' } %> |
<%= link_to 'Update', edit_article_path(@article) %> |
<%= link_to 'Return to Articles Listing', articles_path, data: { confirm: 'Are you sure?' } %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlphaBlog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <% flash.each do |name,msg|%>
      <%= msg%>
    <%end%>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>This is About page</h1>
<%= link_to 'Return to Articles Listing', articles_path, data: { confirm: 'Are you sure?' } %>
<%= link_to 'Home Page' , root_path%>

app/views/pages/home.html.erb
<h1>This is home page</h1>
<%= link_to 'Return to Articles Listing', articles_path, data: { confirm: 'Are you sure?' } %>
<%= link_to 'About Page' , about_path%>